[package]
name = "discrete-log-contract-playground"
version = "0.1.0"
authors = ["Admin <samdpedraza@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoincore-rpc = "0.12.0"
bitcoin = "0.25.2"